version: '3'
services:
  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: br1
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeep:2181
      KAFKA_BROKER_ID: 228
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://br1:29092,CLIENT://localhost:9092
      KAFKA_LISTENERS: INSIDE://br1:29092,CLIENT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeep
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
