apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-service-config-map
  namespace: clinic
  labels:
    app: appointment-service
    tier: backend
data:
  SERVER_PORT: "80"
  PG_HOST: "host.docker.internal"
  PG_PORT: "5432"
  PG_DB_NAME: "clinic"