apiVersion: v1
kind: Service
metadata:
  name: appointment-service-service
  namespace: clinic
  labels:
    app: appointment-service
    tier: backend
spec:
  selector:
    app: appointment-service
  ports:
    - port: 666
      targetPort: 80
      protocol: TCP
  type: NodePort