apiVersion: v1
kind: ConfigMap
metadata:
  name: doctor-service-config-map
  namespace: clinic
  labels:
    app: doctor-service
    tier: backend
data:
  SERVER_PORT: "80"
  MONGO_DB_HOST: "host.docker.internal"
  MONGO_DB_PORT: "27017"
  MONGO_DB_NAME: "clinic"