apiVersion: v1
kind: Secret
metadata:
  name: doctor-service-secret
  namespace: clinic
  labels:
    app: doctor-service
    tier: backend
data:
  MONGO_DB_USER: "dXNlcjE="
  MONGO_DB_PASSWORD: "MzQ1MjU="