apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
      tier: backend
  template:
    metadata:
      labels:
        app: client-service
        tier: backend
    spec:
      containers:
        - name: client-service
          image: ooandioo/client-service:0.0.2
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://user1:34525@host.docker.internal:27017/clinic