server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    path: /appointment-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html