server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/clinic
    user: admin
    password: admin

springdoc:
  api-docs:
    enabled: true
    path: /appointment-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus