apiVersion: v1
kind: Service
metadata:
  name: client-service-service
  namespace: clinic
spec:
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 80
  type: NodePort