apiVersion: v1
kind: Secret
metadata:
  name: client-service-secret
  namespace: clinic
  labels:
    app: client-service
    tier: backend
data:
  MONGO_DB_USER: "dXNlcjE="
  MONGO_DB_PASSWORD: "MzQ1MjU="
